#!/usr/bin/env bash
# exit on error
set -o errexit

export FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
export FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
export FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
export FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
export FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
export FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}

echo "test log :"
echo ${FIREBASE_API_KEY}

yarn && yarn build